### ISSUE TITLE
 header, image_data = request_data.split(';base64,')

### ISSUE THREAD

**Issue by G-Slient** [Emmarex/naijahacks-fort-API#1]
At this line i am getting an error 'InMemoryUploadedFile' object has no attribute 'split' can any one help me with this issue ?

**Comment by Emmarex** [comment]
@G-Slient Can you give more details on the request you are sending?

**Comment by Emmarex** [comment]
@G-Slient you are to send a base64 encoded version of your image.

**Comment by G-Slient** [comment]
![screenshot from 2018-12-26 18-31-10](https://user-images.githubusercontent.com/37027189/50446722-76f58380-093c-11e9-8d39-f88cca2b5f8d.png)
@Emmarex  Sorry for commenting for small doubts now i am getting image not found even after sending image in base64. could u tell me what is the problem now?

thank you for ur immediate reponse
