### ISSUE TITLE
How to run this code in system linux envirnonment can you help me in this 

### ISSUE THREAD

**Issue by mady143** [Emmarex/naijahacks-fort-API#3]
Hi bro,
          Can you help me how run this project with detailed introduction through a file that help me use full to know about your project that helps me a lot or you can contact me , please give the response of my request 

Thanks and Regards,
Manikantha Sekhar Musunuri,
+91 8099906827.
Happy Codding.....

**Comment by Emmarex** [comment]
Hello,

You can check out this links:

“Plant AI — Plant Disease Detection using Convolutional Neural Network” by
Oluwafemi Tairu https://link.medium.com/cHMGTkopmZ

“Plant AI — Deploying Deep Learning Models” by Oluwafemi Tairu
https://link.medium.com/0u8uzdxpmZ
